### ISSUE TITLE
Django Выдаёт ошибку с апишником

### ISSUE THREAD

**Issue by KessPenGames** [teleport2/Py-SPW#1]
Здравствуйте, у меня есть сайт основанный на СПАпи, и Django выдаёт ошибку с вашим апишником когда я попытался сделать миграцию:
```
  File "D:\PoopMarketSite\PoopMarket\views.py", line 7, in <module>
    import pyspw
  File "C:\Users\Svyatoslav\AppData\Local\Programs\Python\Python39\lib\site-packages\pyspw\__init__.py", line 1, in <module>
    from . import api
  File "C:\Users\Svyatoslav\AppData\Local\Programs\Python\Python39\lib\site-packages\pyspw\api.py", line 12, in <module>
    class sp_api_base:
  File "C:\Users\Svyatoslav\AppData\Local\Programs\Python\Python39\lib\site-packages\pyspw\api.py", line 65, in sp_api_base
    def get_user(self, discord_id: str) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by teleport2** [comment]
Здравствуйте, какая у вас версия Python и библиотеки?

**Comment by KessPenGames** [comment]
> Здравствуйте, какая у вас версия Python и библиотеки?

Версия Python: 3.9.5
Версия Django: 4.0.6

**Comment by teleport2** [comment]
А какая версия Py-SPW?

**Comment by KessPenGames** [comment]
> А какая версия Py-SPW?

Самая последняя

**Comment by KessPenGames** [comment]
Я щяс проверил ваш API без Django, все-равно не работает, та-же ошибка.

**Comment by KessPenGames** [comment]
Ой извиняюсь, я щяс перепроверил, у меня версия 1.3

**Comment by KessPenGames** [comment]
При попытке обновится вылезает такая ошибка
![image](https://user-images.githubusercontent.com/75772773/182063281-384a36fc-c51f-410a-b3c8-28e9bec0112c.png)

**Comment by KessPenGames** [comment]
Я обновил ваш Api до 1.4.3 мануально, но там была тоже ошибка.
```
Traceback (most recent call last):
  File "D:\python\test_spw.py", line 1, in <module>
    import pyspw
  File "C:\Users\Svyatoslav\AppData\Local\Programs\Python\Python39\lib\site-packages\pyspw\__init__.py", line 1, in <module>
    from . import api
  File "C:\Users\Svyatoslav\AppData\Local\Programs\Python\Python39\lib\site-packages\pyspw\api.py", line 11, in <module>
    from .User import User
  File "C:\Users\Svyatoslav\AppData\Local\Programs\Python\Python39\lib\site-packages\pyspw\User.py", line 7, in <module>
    class User:
  File "C:\Users\Svyatoslav\AppData\Local\Programs\Python\Python39\lib\site-packages\pyspw\User.py", line 8, in User
    def __init__(self, nickname: str | None, use_mojang_api: bool = True):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
Помогло заменить | на ==

**Comment by teleport2** [comment]
Новые версии библиотеки расчитаны на python 3.10. Скоро будет обновление под другие версии python. А пока могу посоветовать обновится до последней версии Python или подождать несколько часов, пока выйдет обновление

**Comment by teleport2** [comment]
Обновляйтесь до версии 1.4.4, там все пофикшено
